# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.

keys:
  - &steveej 6F7069FE6B96E894E60EC45C6EEFA706CB17E89B
  - &age_steveej age1tkvtkw62xy90xc5xdcq836wgyrwlwmdslh76cete5g98vvvhj34qvwdw0g
  - &jost-s D299483493EAE6B2B3D892B6D33548FA55FF167F
  - &age_r-vdp age1wm7aec0vd5trqqvk6n97kh8r3x0jpue9gne9enr92kdjk63f5e8s9gjy0x
  - &dev age1fnmdutanvfsrhadap3qsmncjfa85x82qy8svy98ma4p37dglq45stcwk28
  - &dweb-reverse-proxy age1ygzy9clj0xavlmau0ham7j5nw8yy4z0q8hvkfpdgwc4fcr8nufpqrdxgvx
  - &linux-builder-01 age1kxkr407jz77ljrhgsfwfmv2yvqjprc6unvx389xp2f48xj8r0vqq2wew5r
  - &x64-linux-dev-01 age1vlxerq9j9jd00qvxj2gxds9re4dz2djqmllkhzsf44gz9a5y4ghs7807h9
  - &tfgrid-shared age194xfar0gfdauu2dcxwqk9lh9d0vjfrzzs2ke0ppanpwv9eqxzs2qp7q7cn
  - &buildbot-nix-0 age1w99tzxl88z7ct3ekpatl62wvhrx29pg450qmn822dpmz0evhxqxqy3scux
creation_rules:
  - path_regex: ^(.+/|)secrets/[^/]+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *age_r-vdp
  - path_regex: ^secrets/dweb-reverse-tls-proxy/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *dweb-reverse-proxy
      - *age_r-vdp
  - path_regex: ^secrets/linux-builder-01/[^/]+$
    key_groups:
    - age:
      - *linux-builder-01
      - *age_steveej
      - *age_r-vdp
  - path_regex: ^secrets/x64-linux-dev-01/[^/]+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *x64-linux-dev-01
      - *age_r-vdp
  - path_regex: ^secrets/buildbot-nix-0/[^/]+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *buildbot-nix-0
      - *age_r-vdp
  - path_regex: ^secrets/nomad/.+$
    key_groups:
    - pgp:
      - *steveej
      # - *jost-s
      age:
      - *dweb-reverse-proxy
      - *tfgrid-shared
      - *age_r-vdp
  - path_regex: ^secrets/nomad/admin/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *age_r-vdp
  - path_regex: ^secrets/events-nix-cache/.+$
    key_groups:
    - pgp:
      - *steveej
  - path_regex: ^secrets/dev/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *dev
      - *x64-linux-dev-01
      - *age_r-vdp
  - path_regex: ^secrets/minio/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *dev
      - *x64-linux-dev-01
      - *age_r-vdp
