# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.

keys:
  - &steveej 6F7069FE6B96E894E60EC45C6EEFA706CB17E89B
  - &jost-s D299483493EAE6B2B3D892B6D33548FA55FF167F
  - &dweb-reverse-proxy age1p4udet5m63tccqqpy38d2m90cv4rffe3cn3965jpmakkwcs7t56qvlp2vw
  - &linux-builder-01 age1kxkr407jz77ljrhgsfwfmv2yvqjprc6unvx389xp2f48xj8r0vqq2wew5r

creation_rules:
  - path_regex: ^(.+/|)secrets/[^/]+$
    key_groups:
    - pgp:
      - *steveej
  - path_regex: ^secrets/dweb-reverse-tls-proxy/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *dweb-reverse-proxy
  - path_regex: ^secrets/linux-builder-01/[^/]+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *linux-builder-01
  - path_regex: ^secrets/nomad/.+$
    key_groups:
    - pgp:
      - *steveej
      - *jost-s
      age:
      - *dweb-reverse-proxy
  - path_regex: ^secrets/nomad/admin/.+$
    key_groups:
    - pgp:
      - *steveej
  - path_regex: ^secrets/events-nix-cache/.+$
    key_groups:
    - pgp:
      - *steveej

