# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.

keys:
  - &steveej 6F7069FE6B96E894E60EC45C6EEFA706CB17E89B
  - &dweb-reverse-proxy age1p4udet5m63tccqqpy38d2m90cv4rffe3cn3965jpmakkwcs7t56qvlp2vw

creation_rules:
  - path_regex: ^(.+/|)secrets/[^/]+$
    key_groups:
    - pgp:
      - *steveej
  - path_regex: ^secrets/dweb-reverse-tls-proxy/.+$
    key_groups:
    - pgp:
      - *steveej
      age:
      - *dweb-reverse-proxy