name: Build

on:
  pull_request:
  push:
    branches: [develop]


jobs:
  os:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    name: OS
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: DeterminateSystems/flake-checker-action@v8
      - run: |
          nix build .#build-os-configurations
          ls -lha result/
