name: Check TURN readiness

on:
  # schedule:
  #   - cron: "0 * * * *" every hour
  workflow_dispatch:
    inputs: {}

env: {}

jobs:
  lints:
    name: Check TURN readiness
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run script
      run: nix run .\#turn-readiness-check
